name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: graalvm-community
        java-version: 25
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt clean check +test
